/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PoolsRouteImport } from './routes/pools'
import { Route as NavigatorRouteImport } from './routes/navigator'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KycRouteImport } from './routes/kyc'
import { Route as HomeRouteImport } from './routes/home'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiWithdrawRequestRouteImport } from './routes/api/withdraw-request'
import { Route as ApiWithdrawApproveRouteImport } from './routes/api/withdraw-approve'
import { Route as ApiMpesaStkRouteImport } from './routes/api/mpesa-stk'
import { Route as ApiMpesaCallbackRouteImport } from './routes/api/mpesa-callback'
import { Route as AdminTransactionsRouteImport } from './routes/admin.transactions'
import { Route as AdminKycRouteImport } from './routes/admin.kyc'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PoolsRoute = PoolsRouteImport.update({
  id: '/pools',
  path: '/pools',
  getParentRoute: () => rootRouteImport,
} as any)
const NavigatorRoute = NavigatorRouteImport.update({
  id: '/navigator',
  path: '/navigator',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KycRoute = KycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWithdrawRequestRoute = ApiWithdrawRequestRouteImport.update({
  id: '/api/withdraw-request',
  path: '/api/withdraw-request',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWithdrawApproveRoute = ApiWithdrawApproveRouteImport.update({
  id: '/api/withdraw-approve',
  path: '/api/withdraw-approve',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMpesaStkRoute = ApiMpesaStkRouteImport.update({
  id: '/api/mpesa-stk',
  path: '/api/mpesa-stk',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMpesaCallbackRoute = ApiMpesaCallbackRouteImport.update({
  id: '/api/mpesa-callback',
  path: '/api/mpesa-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTransactionsRoute = AdminTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKycRoute = AdminKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/kyc': typeof KycRoute
  '/login': typeof LoginRoute
  '/navigator': typeof NavigatorRoute
  '/pools': typeof PoolsRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/api/mpesa-callback': typeof ApiMpesaCallbackRoute
  '/api/mpesa-stk': typeof ApiMpesaStkRoute
  '/api/withdraw-approve': typeof ApiWithdrawApproveRoute
  '/api/withdraw-request': typeof ApiWithdrawRequestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/kyc': typeof KycRoute
  '/login': typeof LoginRoute
  '/navigator': typeof NavigatorRoute
  '/pools': typeof PoolsRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/api/mpesa-callback': typeof ApiMpesaCallbackRoute
  '/api/mpesa-stk': typeof ApiMpesaStkRoute
  '/api/withdraw-approve': typeof ApiWithdrawApproveRoute
  '/api/withdraw-request': typeof ApiWithdrawRequestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/kyc': typeof KycRoute
  '/login': typeof LoginRoute
  '/navigator': typeof NavigatorRoute
  '/pools': typeof PoolsRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/api/mpesa-callback': typeof ApiMpesaCallbackRoute
  '/api/mpesa-stk': typeof ApiMpesaStkRoute
  '/api/withdraw-approve': typeof ApiWithdrawApproveRoute
  '/api/withdraw-request': typeof ApiWithdrawRequestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/history'
    | '/home'
    | '/kyc'
    | '/login'
    | '/navigator'
    | '/pools'
    | '/profile'
    | '/signup'
    | '/admin/kyc'
    | '/admin/transactions'
    | '/api/mpesa-callback'
    | '/api/mpesa-stk'
    | '/api/withdraw-approve'
    | '/api/withdraw-request'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/history'
    | '/home'
    | '/kyc'
    | '/login'
    | '/navigator'
    | '/pools'
    | '/profile'
    | '/signup'
    | '/admin/kyc'
    | '/admin/transactions'
    | '/api/mpesa-callback'
    | '/api/mpesa-stk'
    | '/api/withdraw-approve'
    | '/api/withdraw-request'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/history'
    | '/home'
    | '/kyc'
    | '/login'
    | '/navigator'
    | '/pools'
    | '/profile'
    | '/signup'
    | '/admin/kyc'
    | '/admin/transactions'
    | '/api/mpesa-callback'
    | '/api/mpesa-stk'
    | '/api/withdraw-approve'
    | '/api/withdraw-request'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  HistoryRoute: typeof HistoryRoute
  HomeRoute: typeof HomeRoute
  KycRoute: typeof KycRoute
  LoginRoute: typeof LoginRoute
  NavigatorRoute: typeof NavigatorRoute
  PoolsRoute: typeof PoolsRoute
  ProfileRoute: typeof ProfileRoute
  SignupRoute: typeof SignupRoute
  ApiMpesaCallbackRoute: typeof ApiMpesaCallbackRoute
  ApiMpesaStkRoute: typeof ApiMpesaStkRoute
  ApiWithdrawApproveRoute: typeof ApiWithdrawApproveRoute
  ApiWithdrawRequestRoute: typeof ApiWithdrawRequestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pools': {
      id: '/pools'
      path: '/pools'
      fullPath: '/pools'
      preLoaderRoute: typeof PoolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navigator': {
      id: '/navigator'
      path: '/navigator'
      fullPath: '/navigator'
      preLoaderRoute: typeof NavigatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kyc': {
      id: '/kyc'
      path: '/kyc'
      fullPath: '/kyc'
      preLoaderRoute: typeof KycRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/withdraw-request': {
      id: '/api/withdraw-request'
      path: '/api/withdraw-request'
      fullPath: '/api/withdraw-request'
      preLoaderRoute: typeof ApiWithdrawRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/withdraw-approve': {
      id: '/api/withdraw-approve'
      path: '/api/withdraw-approve'
      fullPath: '/api/withdraw-approve'
      preLoaderRoute: typeof ApiWithdrawApproveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mpesa-stk': {
      id: '/api/mpesa-stk'
      path: '/api/mpesa-stk'
      fullPath: '/api/mpesa-stk'
      preLoaderRoute: typeof ApiMpesaStkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mpesa-callback': {
      id: '/api/mpesa-callback'
      path: '/api/mpesa-callback'
      fullPath: '/api/mpesa-callback'
      preLoaderRoute: typeof ApiMpesaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/transactions': {
      id: '/admin/transactions'
      path: '/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AdminTransactionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kyc': {
      id: '/admin/kyc'
      path: '/kyc'
      fullPath: '/admin/kyc'
      preLoaderRoute: typeof AdminKycRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminKycRoute: typeof AdminKycRoute
  AdminTransactionsRoute: typeof AdminTransactionsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminKycRoute: AdminKycRoute,
  AdminTransactionsRoute: AdminTransactionsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  HistoryRoute: HistoryRoute,
  HomeRoute: HomeRoute,
  KycRoute: KycRoute,
  LoginRoute: LoginRoute,
  NavigatorRoute: NavigatorRoute,
  PoolsRoute: PoolsRoute,
  ProfileRoute: ProfileRoute,
  SignupRoute: SignupRoute,
  ApiMpesaCallbackRoute: ApiMpesaCallbackRoute,
  ApiMpesaStkRoute: ApiMpesaStkRoute,
  ApiWithdrawApproveRoute: ApiWithdrawApproveRoute,
  ApiWithdrawRequestRoute: ApiWithdrawRequestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
